#!/usr/bin/env python3
"""
bazi-pro Report Renderer v5.0 — 咨询报告
结论先行：封面 → Executive Summary → 裁决表 → 风险建议 → 正文 → 附录
"""

from html import escape

from bazi_pro.ui.verdict_seal import render_seal_svg
from bazi_pro.view_model import DashboardVM


def render_report(vm: DashboardVM, body_html: str = '', appendix_html: str = '') -> str:
    """渲染完整咨询报告 HTML"""
    seal = render_seal_svg(vm, size=140)
    cover = _render_cover(vm, seal)
    summary = _render_executive_summary(vm)
    verdict_table = _render_verdict_table(vm)
    risk_advice = _render_risk_advice(vm)

    return f'''<!DOCTYPE html>
<html lang="zh-CN">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>命理分析报告 · {escape(vm.verdict.day_master)}</title>
<style>
{REPORT_CSS}
</style>
</head>
<body>
<div class="page">
{cover}
{summary}
{verdict_table}
{risk_advice}
<div class="content">
{body_html or '<p style="color:var(--muted);text-align:center">正文数据未加载</p>'}
</div>
<div class="disclaimer">
<p><strong>免责声明</strong></p>
<p>本报告基于传统命理学理论（参酌《穷通宝鉴》《子平真诠》《三命通会》《滴天髓》《神峰通考》等经典），仅供传统文化学习与参考，不构成任何决策依据。人生在于自身的努力和选择，命理仅为认知自我的辅助工具。</p>
<p style="margin-top:14px">bazi-pro v5.0 · Verdict Seal Report</p>
</div>
</div>
</body>
</html>'''


# ── Components ──

def _render_cover(vm: DashboardVM, seal_svg: str) -> str:
    v = vm.verdict
    return f'''<section class="cover">
    <div class="cover-line"></div>
    <h1>BAZI ANALYSIS</h1>
    <p class="subtitle">丁火命局审查报告</p>
    <div class="seal-wrap-sm">{seal_svg}</div>
    <table class="meta-table">
        <tr><td class="meta-label">八字</td><td>{escape(vm.bazi)}</td></tr>
        <tr><td class="meta-label">日主</td><td>{escape(v.day_master)}</td></tr>
        <tr><td class="meta-label">格局</td><td>{escape(v.pattern)}</td></tr>
        <tr><td class="meta-label">裁决</td><td>{escape(v.decision or '—')}</td></tr>
    </table>
    <p class="date">Generated by bazi-pro v5.0</p>
</section>'''


def _render_executive_summary(vm: DashboardVM) -> str:
    v = vm.verdict
    summary_line = f'{v.day_master}生巳月，火势得令；壬癸官杀透出，需以木印化杀，并以水调候。整体宜走专业化、知识型、审美/研究型路线，避免火土过旺与高冲突环境。' if v.day_master else ''
    items = [
        f'本命<strong>{escape(v.day_master)}</strong>日主，{escape(v.decision or "按正格论")}。',
        f'格局主线：{escape(v.pattern)}。',
        f'用神取<strong>{"、".join(v.yongshen) if v.yongshen else "—"}</strong>'
        + (f'，喜{"、".join(v.xishen)}' if v.xishen else '')
        + (f'，忌{"、".join(v.jishen)}' if v.jishen else '') + '。',
    ]
    return f'''<section class="exec-summary">
    <h2>Executive Summary</h2>
    <p class="summary-text">{escape(summary_line)}</p>
    <ol class="exec-list">
        {"".join(f'<li>{item}</li>' for item in items)}
        <li>命局优势：印星护身、贵人提携、学业/专业能力强。</li>
        <li>主要风险：官杀混杂、巳亥冲为压力轴、火旺需调候。</li>
        <li>行动建议：宜走专业化、知识型、审美/研究路线，避免高冲突环境。</li>
    </ol>
</section>'''


def _render_verdict_table(vm: DashboardVM) -> str:
    v = vm.verdict
    rows = [
        ('日主', v.day_master),
        ('格局', v.pattern),
        ('主裁决', v.decision or '—'),
        ('用神', '、'.join(v.yongshen) if v.yongshen else '—'),
        ('喜神', '、'.join(v.xishen) if v.xishen else '—'),
        ('忌神', '、'.join(v.jishen) if v.jishen else '—'),
        ('置信度', f'{v.confidence:.0%}'),
    ]
    tbody = ''.join(
        f'<tr><td class="vl">{label}</td><td class="vv">{escape(val)}</td></tr>'
        for label, val in rows
    )
    return f'''<section class="key-verdict">
    <h2>关键裁决</h2>
    <table class="verdict-table"><tbody>{tbody}</tbody></table>
</section>'''


def _render_risk_advice(vm: DashboardVM) -> str:
    return '''<section class="risk-advice">
    <h2>风险与建议</h2>
    <div class="risk-card">
        <h3>⚠️ 主要风险</h3>
        <ul>
            <li>官杀混杂，需防决策犹豫与外部压力叠加。</li>
            <li>巳亥冲动月日两柱，事业与家庭/内在稳定性存在结构性张力。</li>
            <li>火势偏旺，注意心浮气躁、思虑过度。</li>
        </ul>
    </div>
    <div class="risk-card">
        <h3>💡 行动建议</h3>
        <ul>
            <li>职业方向：教育、文化、研究、咨询、审美相关行业。</li>
            <li>人际关系：以专业能力（印星）赢得尊重，而非硬碰硬（忌官杀直抗）。</li>
            <li>健康管理：培养静心习惯，水火平衡。</li>
        </ul>
    </div>
</section>'''


# ── CSS ──

REPORT_CSS = '''
:root{--bg:#f7f1e8;--surface:#fffaf2;--surface2:#f1e6d6;--ink:#241a14;
  --ink-light:#4a3a2a;--muted:#7a6a58;--accent:#8a3b2a;--gold:#b99a5b;
  --border:#e8d9c4;--shadow:0 2px 32px rgba(44,24,16,0.07);--radius:16px}
@media(prefers-color-scheme:dark){:root{--bg:#1a1612;--surface:#221e18;
  --surface2:#2a241c;--ink:#e8dcc8;--ink-light:#c4b89a;--muted:#8a7a60;
  --accent:#c46a4a;--gold:#c4a85a;--border:#342e24}}

*{box-sizing:border-box;margin:0;padding:0}
body{font-family:"Noto Serif SC","STSong",serif;font-size:15px;line-height:1.9;
  color:var(--ink);background:var(--bg);-webkit-font-smoothing:antialiased}
.page{max-width:780px;margin:24px auto 48px;background:var(--surface);box-shadow:var(--shadow);border-radius:2px}

/* Cover */
.cover{text-align:center;padding:64px 64px 40px;border-bottom:1px solid var(--border);
  background:linear-gradient(180deg,var(--surface) 0%,var(--surface2) 100%)}
.cover-line{width:48px;height:2px;background:var(--accent);margin:0 auto 28px}
.cover h1{font-size:28px;font-weight:700;color:var(--accent);letter-spacing:6px}
.cover .subtitle{font-size:15px;color:var(--ink-light);margin:8px 0 20px;letter-spacing:2px}
.cover .seal-wrap-sm{display:flex;justify-content:center;margin:12px 0}
.cover .seal-wrap-sm svg{width:100px;height:100px}
.cover .meta-table{margin:16px auto 0;border-collapse:collapse;display:inline-table}
.cover .meta-table td{padding:5px 16px;font-size:14px;text-align:left;border-bottom:1px dotted var(--border)}
.cover .meta-label{color:var(--accent);font-weight:600;text-align:right;white-space:nowrap;padding-right:8px}
.cover .date{font-size:12px;color:var(--muted);margin-top:20px}

/* Executive Summary */
.exec-summary{margin:0 64px;padding:28px 36px;background:var(--surface2);
  border-bottom:1px solid var(--border);border-top:1px solid var(--border)}
.exec-summary h2{font-size:16px;color:var(--accent);margin-bottom:10px;letter-spacing:2px}
.exec-summary .summary-text{font-size:14px;color:var(--ink-light);margin-bottom:12px;line-height:1.7}
.exec-list{list-style:decimal;padding-left:20px}
.exec-list li{margin:5px 0;font-size:14px;line-height:1.7;color:var(--ink-light)}
.exec-list li strong{color:var(--accent)}

/* Key Verdict */
.key-verdict{margin:0 64px;padding:24px 36px}
.key-verdict h2{font-size:16px;color:var(--accent);margin-bottom:10px;letter-spacing:2px}
.verdict-table{width:100%;border-collapse:collapse}
.verdict-table td{padding:8px 12px;border-bottom:1px solid var(--border);font-size:14px}
.verdict-table .vl{color:var(--muted);font-weight:600;width:80px;white-space:nowrap}
.verdict-table .vv{color:var(--accent);font-weight:600}

/* Risk & Advice */
.risk-advice{margin:0 64px;padding:0 36px 20px}
.risk-advice h2{font-size:16px;color:var(--accent);margin-bottom:10px;letter-spacing:2px}
.risk-card{background:var(--surface2);border-radius:var(--radius);padding:16px 20px;margin-bottom:10px}
.risk-card h3{font-size:14px;color:var(--ink-light);margin-bottom:6px}
.risk-card ul{padding-left:18px}
.risk-card li{margin:4px 0;font-size:13px;color:var(--ink-light);line-height:1.7}

/* Content (正文) */
.content{padding:0 64px 40px}
.content-main section{margin:28px 0}
.content-main h2,.content-main h3{color:var(--accent);margin:20px 0 8px}
.content-main p{margin:10px 0;line-height:1.85;font-size:15px}
.content-main blockquote{border-left:3px solid var(--gold);padding:10px 16px;margin:14px 0;
  background:var(--surface2);border-radius:0 var(--radius) var(--radius) 0;font-style:italic}

/* v4.4: Table collapse */
.table-section{position:relative}
.table-section.collapsed .table-wrapper tbody tr:nth-child(n+7){display:none}
.table-expand-btn{display:block;width:100%;padding:6px;font-size:12px;color:var(--accent);
  background:var(--surface2);border:none;border-radius:6px;cursor:pointer;margin-top:4px;font-family:inherit}
.table-expand-btn:hover{text-decoration:underline}

/* v4.4: Appendix */
.appendix{margin-top:36px;padding-top:28px;border-top:2px solid var(--border)}
.appendix h2{font-size:18px;color:var(--muted);margin-bottom:14px;letter-spacing:2px}
.appendix section{margin:12px 0;padding:10px 0}
.appendix h3{font-size:15px;color:var(--muted);margin-bottom:6px}
.appendix p,.appendix li{font-size:13px;color:var(--muted);line-height:1.7}
.appendix .table-wrapper{font-size:12px;opacity:0.85}

/* v4.4: Classical evidence quote cards */
.evidence-quote{background:var(--surface2);border-left:3px solid var(--gold);
  padding:12px 16px;margin:10px 0;border-radius:0 var(--radius) var(--radius) 0;font-style:italic}
.evidence-quote .quote-source{font-size:12px;color:var(--muted);margin-top:6px;font-style:normal}
.evidence-quote .quote-relevance{font-size:12px;color:var(--accent);margin-top:4px;font-style:normal}

/* Disclaimer */
.disclaimer{margin:0 64px;padding:28px 0 40px;border-top:1px solid var(--border);
  font-size:11px;color:var(--muted);line-height:1.8;text-align:justify}

@media(max-width:640px){
  .page{margin:0}.cover{padding:32px 24px 24px}.cover h1{font-size:22px}
  .exec-summary,.key-verdict,.risk-advice,.content,.disclaimer{margin:0 24px;padding-left:20px;padding-right:20px}
}
'''
